services:
  db:
    image: "mariadb:11.4.1-rc-jammy"
    container_name: "mariadb"
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3306:3306"
    volumes:
      - "mariadbconf:/etc/mysql/conf.d"
      - "mariadbdblogs:/var/log"
      - "mariadblib:/var/lib/mysql"
      - "./data:/opt/dump"
    networks:
      - mariadb-network

  adminer:
    image: phpmyadmin:5.1.1-apache
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - mariadb-network

volumes:
  mariadbconf:
  mariadbdblogs:
  mariadblib:

networks:
  mariadb-network:
    driver: bridge